# Generated by Django 5.1.15 on 2026-08-27 04:22

import apps.accounts.managers
import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='E.164 format, e.g. +27821234567. Collected at onboarding, verified later.', max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('handle', models.SlugField(help_text='Public URL: /u/<handle>/', max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False, help_text='Suspended users can log in but cannot post, list or request intros.')),
                ('suspension_reason', models.CharField(blank=True, max_length=200)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=6)),
                ('destination', models.CharField(db_index=True, help_text='Email address or E.164 phone number.', max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('login', 'Log in or sign up'), ('phone', 'Verify phone number'), ('email_change', 'Change email address')], default='login', max_length=14)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/')),
                ('avatar_thumb', models.ImageField(blank=True, upload_to='avatars/thumbs/%Y/%m/')),
                ('whatsapp_ok', models.BooleanField(default=True, help_text='Show a WhatsApp button once contacts are released.')),
                ('hide_from_search', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('suburb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='geo.suburb')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('licence_verified_at', models.DateTimeField(blank=True, null=True)),
                ('licence_expires_on', models.DateField(blank=True, null=True)),
                ('prdp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('prdp_expires_on', models.DateField(blank=True, null=True)),
                ('references_checked_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_manually_by', models.ForeignKey(blank=True, help_text='Set when staff confirm a number over WhatsApp instead of by SMS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones_verified', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('id', 'ID / Passport'), ('licence', "Driver's licence"), ('prdp', 'Professional Driving Permit'), ('reg', 'Vehicle registration (NaTIS)'), ('addr', 'Proof of address')], max_length=12)),
                ('file', models.FileField(blank=True, upload_to=apps.accounts.models.kyc_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('expires_on', models.DateField(blank=True, help_text='Expiry printed on the document, if any.', null=True)),
                ('purge_after', models.DateField()),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['handle'], name='accounts_us_handle_23c711_idx'),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['destination', 'is_used', 'expires_at'], name='accounts_ot_destina_26343d_idx'),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['channel', 'created_at'], name='accounts_ot_channel_649b84_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ve_status_200a4f_idx'),
        ),
    ]
