# Generated by Django 5.2.17 on 2026-09-03 08:54

import apps.accounts.models
import apps.accounts.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(blank=True, storage=apps.accounts.storages.kyc_storage, upload_to=apps.accounts.models.kyc_upload_path),
        ),
    ]
