# Generated by Django 5.2.17 on 2026-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_verificationdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of published reviews received. Null until there are any.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
