"""
Phone verification is removed.

The SMS round-trip gated listing a car, requesting and approving an
introduction, and claiming an imported advert. The cost of it fell on honest
members at the exact moment they were trying to do something useful, while the
checks that carry real weight — ID, licence, PrDP — sit further up the ladder
and are untouched.

Numbers themselves are NOT dropped. `User.phone` stays: the product's whole
mechanic is releasing a phone number once an introduction is approved.

WHAT THIS DELETES, AND WHY IT IS NOT REVERSIBLE
-----------------------------------------------
`phone_verified_at` and `phone_verified_manually_by` hold who had verified and
which staff member confirmed it. Reversing this migration recreates the columns
empty — the history is gone. That is the intended outcome rather than an
oversight: the ladder no longer has a rung for it, so retaining the data would
mean keeping a record nothing can read.

The OTP `channel` column goes with it. Email was the only other value, so the
column would be the same string in every row, and the index on it existed only
to total up an SMS bill that no longer accrues.
"""

# Generated by Django 5.2.17 on 2026-09-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_country'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpchallenge',
            name='accounts_ot_channel_649b84_idx',
        ),
        migrations.RemoveField(
            model_name='otpchallenge',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='phone_verified_at',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='phone_verified_manually_by',
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('login', 'Log in or sign up'), ('email_change', 'Change email address')], default='login', max_length=14),
        ),
    ]
