# Generated by Django 5.2.17 on 2026-09-17 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


"""
Interest replaces IntroRequest as the way a conversation starts, and number
sharing moves from a pair-level fact to a per-thread, per-person one.

Nothing is dropped. Existing approved introductions still open a thread and
still lift redaction, so no conversation that worked yesterday stops working.
"""


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_vehiclelisting_odometer_by'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='a_shared_number_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='b_shared_number_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='listings.driverlisting')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='messaging.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
                ('vehicle_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['thread', '-created_at'], name='messaging_i_thread__281a81_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'vehicle_listing'), name='one_interest_per_vehicle'), models.UniqueConstraint(fields=('user', 'driver_listing'), name='one_interest_per_driver_listing'), models.CheckConstraint(condition=models.Q(models.Q(('driver_listing__isnull', True), ('vehicle_listing__isnull', False)), models.Q(('driver_listing__isnull', False), ('vehicle_listing__isnull', True)), _connector='OR'), name='interest_names_exactly_one_listing')],
            },
        ),
    ]
