# Generated by Django 5.2.17 on 2026-09-17 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', '-created_at'], name='follows_fol_followe_3118ce_idx'), models.Index(fields=['following', '-created_at'], name='follows_fol_followi_47011c_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='one_follow_per_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='cannot_follow_yourself')],
            },
        ),
    ]
