# Generated by Django 5.2.17 on 2026-09-03 13:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intros', '0001_initial'),
        ('listings', '0004_listing_owner_or_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('agreed', 'We agreed to end it'), ('driver_left', 'The driver moved on'), ('owner_ended', 'The owner ended it'), ('payment', 'Payment problems'), ('vehicle', 'Problems with the car'), ('conduct', 'Conduct'), ('other', 'Something else')], max_length=20)),
                ('confirmed_by_owner', models.BooleanField(default=False)),
                ('confirmed_by_driver', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements_as_driver', to=settings.AUTH_USER_MODEL)),
                ('intro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='intros.introrequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements_as_owner', to=settings.AUTH_USER_MODEL)),
                ('vehicle_listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['-started_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('payment_reliability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('vehicle_care', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fairness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('maintenance_response', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('deposit_returned', models.BooleanField(blank=True, null=True)),
                ('body', models.TextField(blank=True, max_length=1500)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='placements.placement')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['owner', '-started_on'], name='placements__owner_i_89a963_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['driver', '-started_on'], name='placements__driver__6db439_idx'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('vehicle_listing', 'driver'), name='one_open_placement_per_driver_per_car'),
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.CheckConstraint(condition=models.Q(('owner', models.F('driver')), _negated=True), name='placement_needs_two_people'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['subject', 'is_published', '-published_at'], name='placements__subject_caece4_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('placement', 'author'), name='one_review_per_person_per_placement'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('author', models.F('subject')), _negated=True), name='cannot_review_yourself'),
        ),
    ]
