# Generated by Django 5.2.17 on 2026-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('ad', 'Ad box (top of the rail)'), ('rail', 'Carousel (under the ad box)')], default='rail', max_length=6)),
                ('kind', models.CharField(choices=[('feature', 'Feature'), ('benefit', 'Benefit'), ('testimonial', 'Testimonial'), ('business', 'Business advert'), ('notice', 'Notice')], default='feature', max_length=12)),
                ('animation', models.CharField(choices=[('shuffle', 'Surprise me'), ('fade', 'Fade through'), ('slide', 'Slide up'), ('zoom', 'Zoom in'), ('flip', 'Flip'), ('swipe', 'Swipe across')], default='shuffle', help_text='Ad box only. Carousel slides always crawl sideways.', max_length=10)),
                ('title', models.CharField(max_length=80)),
                ('body', models.CharField(blank=True, help_text='One sentence. A rail is read out of the corner of an eye.', max_length=180)),
                ('image', models.ImageField(blank=True, upload_to='promos/')),
                ('image_alt', models.CharField(blank=True, help_text='What the picture shows. Leave blank if it is decoration.', max_length=140)),
                ('url', models.CharField(blank=True, help_text='Where the card goes when clicked. Site path or full URL. Blank makes it a non-clickable card.', max_length=300)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['slot', 'is_active', 'sort_order'], name='promos_prom_slot_dbb19b_idx')],
            },
        ),
    ]
