# Generated by Django 5.1.15 on 2026-08-27 04:40

import apps.listings.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(choices=[('ZA', 'South Africa'), ('ZW', 'Zimbabwe')], default='ZA', max_length=2)),
                ('max_vehicle_age_years', models.PositiveSmallIntegerField(blank=True, help_text="Leave blank unless you've confirmed the platform's current rule.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)])),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=10)),
                ('colour', models.CharField(blank=True, max_length=30)),
                ('arrangement', models.CharField(choices=[('weekly', 'Fixed weekly rental'), ('daily', 'Daily rental'), ('share', 'Earnings share'), ('rent2own', 'Rent to own')], max_length=10)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earnings_share_pct', models.PositiveSmallIntegerField(blank=True, help_text="Driver's share of gross earnings.", null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('rent_to_own_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_paid_by', models.CharField(choices=[('owner', 'Owner pays'), ('driver', 'Driver pays'), ('shared', 'Shared'), ('na', 'Not applicable')], default='driver', max_length=8)),
                ('maintenance_paid_by', models.CharField(choices=[('owner', 'Owner pays'), ('driver', 'Driver pays'), ('shared', 'Shared'), ('na', 'Not applicable')], default='owner', max_length=8)),
                ('insurance_paid_by', models.CharField(choices=[('owner', 'Owner pays'), ('driver', 'Driver pays'), ('shared', 'Shared'), ('na', 'Not applicable')], default='owner', max_length=8)),
                ('licensing_paid_by', models.CharField(choices=[('owner', 'Owner pays'), ('driver', 'Driver pays'), ('shared', 'Shared'), ('na', 'Not applicable')], default='owner', max_length=8)),
                ('tracker_paid_by', models.CharField(choices=[('owner', 'Owner pays'), ('driver', 'Driver pays'), ('shared', 'Shared'), ('na', 'Not applicable')], default='owner', max_length=8)),
                ('has_tracker', models.BooleanField(default=False)),
                ('has_insurance', models.BooleanField(default=False)),
                ('weekly_km_limit', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True)),
                ('min_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('requires_prdp', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Live'), ('paused', 'Paused'), ('placed', 'Driver placed'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('boost_expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_listings', to=settings.AUTH_USER_MODEL)),
                ('platforms', models.ManyToManyField(blank=True, related_name='listings', to='listings.platform')),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='geo.suburb')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.listings.models.listing_photo_path)),
                ('thumbnail', models.ImageField(blank=True, upload_to=apps.listings.models.listing_photo_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status', 'suburb'], name='listings_ve_status_b86863_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status', '-created_at'], name='listings_ve_status_b23421_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['owner', 'status'], name='listings_ve_owner_i_6b4b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['status', 'arrangement', 'weekly_rate'], name='listings_ve_status_24b67c_idx'),
        ),
        migrations.AddIndex(
            model_name='listingphoto',
            index=models.Index(fields=['listing', 'order'], name='listings_li_listing_b8d2a4_idx'),
        ),
    ]
