# Generated by Django 5.2.17 on 2026-08-27 13:54

import apps.listings.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('headline', models.CharField(help_text='The one line an owner reads first.', max_length=120)),
                ('years_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('licence_code', models.CharField(choices=[('B', 'Code B — light vehicle'), ('EB', 'Code EB — light vehicle and trailer'), ('C1', 'Code C1 — heavy vehicle'), ('C', 'Code C — heavy vehicle'), ('EC1', 'Code EC1 — heavy vehicle and trailer'), ('EC', 'Code EC — articulated')], default='B', max_length=5)),
                ('has_prdp', models.BooleanField(default=False)),
                ('preferred_arrangement', models.CharField(blank=True, choices=[('weekly', 'Fixed weekly rental'), ('daily', 'Daily rental'), ('share', 'Earnings share'), ('rent2own', 'Rent to own')], max_length=10)),
                ('max_weekly_rate', models.DecimalField(blank=True, decimal_places=2, help_text="The most you're willing to pay a week. Leave blank if it depends.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=1500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Live'), ('paused', 'Paused'), ('placed', 'Driving a car'), ('archived', 'Archived')], default='active', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_listings', to=settings.AUTH_USER_MODEL)),
                ('home_suburb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.suburb')),
                ('platforms_experience', models.ManyToManyField(blank=True, related_name='driver_listings', to='listings.platform')),
                ('work_suburbs', models.ManyToManyField(blank=True, related_name='driver_listings', to='geo.suburb')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'home_suburb'], name='listings_dr_status_17c184_idx'), models.Index(fields=['status', '-created_at'], name='listings_dr_status_24111e_idx'), models.Index(fields=['driver', 'status'], name='listings_dr_driver__bcc4de_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformRatingProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('trips', models.PositiveIntegerField(blank=True, help_text='Completed trips, if the screen shows them.', null=True)),
                ('screenshot', models.ImageField(blank=True, upload_to=apps.listings.models.rating_proof_path)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('purge_after', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_proofs', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_proofs', to='listings.platform')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='listings_pl_status_7f170b_idx')],
                'constraints': [models.UniqueConstraint(fields=('driver', 'platform'), name='uniq_rating_proof_per_platform')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('cars', 'Cars'), ('drivers', 'Drivers')], max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('never', "Don't alert me")], default='daily', max_length=10)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'label'), name='uniq_saved_search_label')],
            },
        ),
    ]
