# Generated by Django 5.2.17 on 2026-09-03 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('listings', '0002_driverlisting_platformratingproof_savedsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, help_text='Anything that helps us match you to the original post.', max_length=600)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_imported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='source',
            field=models.CharField(choices=[('user', 'Posted by the owner'), ('facebook', 'Copied from Facebook')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='source_author_name',
            field=models.CharField(blank=True, help_text='Who posted the original, as shown on the post. For credit, nothing else.', max_length=80),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='source_posted_at',
            field=models.DateTimeField(blank=True, help_text='When the original went up, if the post shows it.', null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to the original post. Required on an import — it is the attribution.', max_length=500),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null on an imported advert nobody has claimed yet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vehiclelisting',
            index=models.Index(fields=['source', 'status'], name='listings_ve_source_1e7892_idx'),
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='listings.vehiclelisting'),
        ),
        migrations.AddField(
            model_name='listingclaim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listingclaim',
            index=models.Index(fields=['status', 'created_at'], name='listings_li_status_a86dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingclaim',
            constraint=models.UniqueConstraint(fields=('listing', 'claimant'), name='uniq_claim_per_listing_per_user'),
        ),
    ]
