# Generated by Django 5.2.17 on 2026-09-03 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('listings', '0003_imported_adverts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehiclelisting',
            constraint=models.CheckConstraint(condition=models.Q(('owner__isnull', False), models.Q(('source_url', ''), _negated=True), _connector='OR'), name='listing_has_an_owner_or_a_source'),
        ),
    ]
