# Generated by Django 5.2.17 on 2026-09-17 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_owner_or_source'),
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('repair', 'Repair'), ('incident', 'Incident'), ('payment', 'Payment'), ('licensing', 'Licensing'), ('other', 'Note')], default='other', max_length=10)),
                ('body', models.TextField(max_length=2000)),
                ('happened_on', models.DateField()),
                ('odometer_km', models.PositiveIntegerField(blank=True, help_text="Optional. What makes a service history answer 'when is the next one due' rather than only 'when was the last one'.", null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_notes', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='listings.vehiclelisting')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_notes', to='placements.placement')),
            ],
            options={
                'ordering': ['-happened_on', '-created_at'],
                'indexes': [models.Index(fields=['listing', '-happened_on'], name='listings_ve_listing_79f832_idx'), models.Index(fields=['listing', 'kind', '-happened_on'], name='listings_ve_listing_592faa_idx')],
            },
        ),
    ]
