# Generated by Django 5.2.17 on 2026-09-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_vehicle_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='odometer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='service_interval_km',
            field=models.PositiveIntegerField(blank=True, help_text='How often this car needs a service, in kilometres.', null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='service_warn_km',
            field=models.PositiveIntegerField(default=1000, help_text='How far ahead to warn. 1000 on a 15000 interval warns at 14000 and again at 15000.'),
        ),
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('warning', 'Service coming up'), ('due', 'Service due')], max_length=7)),
                ('due_at_km', models.PositiveIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='listings.vehiclelisting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('listing', 'stage', 'due_at_km'), name='one_service_reminder_per_stage_per_cycle')],
            },
        ),
    ]
