# Generated by Django 5.2.17 on 2026-09-03 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=140, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('mechanic', 'Mechanic'), ('panel', 'Panel beater'), ('tyres', 'Tyres'), ('tracker', 'Tracker'), ('insurance', 'Insurance'), ('carwash', 'Car wash'), ('spares', 'Spares'), ('dashcam', 'Dashcam'), ('school', 'Driving school')], max_length=12)),
                ('description', models.TextField(max_length=1500)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='biz/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Live'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by staff. The row stays so the moderation trail does.')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to=settings.AUTH_USER_MODEL)),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='geo.suburb')),
            ],
            options={
                'ordering': ['-is_paid', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_hidden', 'category'], name='directory_b_status_6afd8b_idx'), models.Index(fields=['status', 'is_hidden', 'suburb'], name='directory_b_status_84b1d0_idx')],
            },
        ),
    ]
