# Generated by Django 5.2.17 on 2026-09-03 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_listing_owner_or_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(max_length=400)),
                ('status', models.CharField(choices=[('pending', 'Waiting for a reply'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('credits_charged', models.PositiveSmallIntegerField(default=0)),
                ('contacts_released_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('driver_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intro_requests', to='listings.driverlisting')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intros_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intros_received', to=settings.AUTH_USER_MODEL)),
                ('vehicle_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intro_requests', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'status', '-created_at'], name='intros_intr_to_user_633e00_idx'), models.Index(fields=['from_user', 'status', '-created_at'], name='intros_intr_from_us_6a6b59_idx'), models.Index(fields=['status', 'expires_at'], name='intros_intr_status_0d1bd7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'vehicle_listing'), name='one_pending_intro_per_vehicle'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'driver_listing'), name='one_pending_intro_per_driver'), models.CheckConstraint(condition=models.Q(models.Q(('driver_listing__isnull', True), ('vehicle_listing__isnull', False)), models.Q(('driver_listing__isnull', False), ('vehicle_listing__isnull', True)), _connector='OR'), name='intro_names_exactly_one_listing')],
            },
        ),
    ]
