# Generated by Django 5.2.17 on 2026-09-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like_to_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='one_reaction_per_post_per_user',
        ),
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='feed.comment'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='feed.post'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['comment', 'kind'], name='feed_reacti_comment_fc0e49_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', True)), fields=('post', 'user'), name='one_reaction_per_post_per_user'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('comment', 'user'), name='one_reaction_per_comment_per_user'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='reaction_targets_exactly_one_thing'),
        ),
    ]
