# Generated by Django 5.2.17 on 2026-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Hide the author from members. Staff can still see who posted.'),
        ),
    ]
