# Generated by Django 5.2.17 on 2026-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_post_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anon_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
