# Generated by Django 5.1.15 on 2026-08-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('ZA', 'South Africa'), ('ZW', 'Zimbabwe')], default='ZA', max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('is_launch_market', models.BooleanField(default=False, help_text='Only launch markets are shown in signup. Seed one metro at a time.')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='geo.province')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suburbs', to='geo.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'slug'), name='uniq_city_slug_per_province'),
        ),
        migrations.AddIndex(
            model_name='suburb',
            index=models.Index(fields=['latitude', 'longitude'], name='geo_suburb_latitud_079519_idx'),
        ),
        migrations.AddIndex(
            model_name='suburb',
            index=models.Index(fields=['city', 'name'], name='geo_suburb_city_id_fa2f81_idx'),
        ),
        migrations.AddConstraint(
            model_name='suburb',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='uniq_suburb_slug_per_city'),
        ),
    ]
