# Generated by Django 5.2.17 on 2026-09-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_launch_market',
            field=models.BooleanField(default=False, help_text='Marks a metro we opened deliberately. It no longer restricts who may sign up or list — members type their own city — so this is a label for reporting, not a gate.'),
        ),
    ]
