# Generated by Django 5.2.17 on 2026-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('intro_requested', 'Introduction requested'), ('intro_approved', 'Introduction approved'), ('intro_declined', 'Introduction declined'), ('placement_confirm', 'Placement needs confirming'), ('placement_confirmed', 'Placement confirmed'), ('review_published', 'Review published'), ('post_comment', 'New comment'), ('comment_reply', 'New reply'), ('claim_approved', 'Claim approved'), ('claim_rejected', 'Claim rejected'), ('business_verified', 'Business verified'), ('new_follower', 'New follower')], max_length=20),
        ),
    ]
